-- Phase 5.26 - Core ChronoTrade solutions for the Need Engine.
-- These rows are the real first matching base. Admin/CMS can edit them later.

insert into public.solutions (
  type,
  name,
  slug,
  description,
  problems_solved,
  target_users,
  industries,
  price_model,
  price,
  recurring,
  internal_or_external,
  active,
  public,
  metadata
)
values
  (
    'SERVICE',
    'ChronoTrade Vision',
    'chronotrade-vision',
    'Clarifier une idee, une direction ou un potentiel projet avant de depenser du temps et de l argent.',
    array['idee floue','pas de direction','choix de projet','positionnement','priorites','roadmap'],
    array['entrepreneur','independant','createur','porteur de projet','PME'],
    array['services','commerce','digital','artisanat','restauration','consulting'],
    'sur_devis',
    null,
    false,
    'internal',
    true,
    true,
    '{"universe":"vision","accent":"violet","cta":"Clarifier mon idee","form":"vision"}'::jsonb
  ),
  (
    'SERVICE',
    'ChronoTrade Launch',
    'chronotrade-launch',
    'Transformer une idee en lancement concret avec une offre, une structure et un plan d action clair.',
    array['lancement','offre','business model','plan d action','premiers clients','strategie de lancement'],
    array['createur','entrepreneur','startup','independant','PME'],
    array['services','commerce','digital','consulting','local business'],
    'sur_devis',
    null,
    false,
    'internal',
    true,
    true,
    '{"universe":"launch","accent":"gold","cta":"Lancer mon projet","form":"launch"}'::jsonb
  ),
  (
    'SERVICE',
    'ChronoTrade Studio',
    'chronotrade-studio',
    'Construire une image professionnelle, un site clair et une presence digitale qui inspire confiance.',
    array['site web','landing page','logo','branding','identite visuelle','image professionnelle','presence digitale'],
    array['entreprise','independant','artisan','restaurant','consultant','PME'],
    array['services','commerce','restauration','immobilier','bien etre','consulting'],
    'sur_devis',
    null,
    false,
    'internal',
    true,
    true,
    '{"universe":"studio","accent":"silver-blue","cta":"Lancer Studio","form":"studio"}'::jsonb
  ),
  (
    'SERVICE',
    'ChronoTrade OS',
    'chronotrade-os',
    'Automatiser les taches repetitives, connecter les outils et integrer l IA dans les processus utiles.',
    array['automatisation','intelligence artificielle','gain de temps','workflow','crm','email','messages clients','dashboard','outils connectes'],
    array['entreprise','independant','PME','equipe commerciale','service client'],
    array['services','ecommerce','formation','agence','immobilier','consulting'],
    'sur_devis',
    null,
    false,
    'internal',
    true,
    true,
    '{"universe":"os","accent":"electric-purple","cta":"Decouvrir OS","form":"os"}'::jsonb
  ),
  (
    'SERVICE',
    'ChronoTrade Business',
    'chronotrade-business',
    'Qualifier un besoin, trouver les bons partenaires et transformer un blocage en decision concrete.',
    array['partenaires','mise en relation','reseau','prestataire','developpement commercial','opportunites','trouver des clients'],
    array['entreprise','entrepreneur','partenaire','freelance','PME'],
    array['services','commerce','digital','immobilier','artisanat','consulting'],
    'sur_devis',
    null,
    false,
    'internal',
    true,
    true,
    '{"universe":"business","accent":"gold","cta":"Activer Business","form":"business"}'::jsonb
  ),
  (
    'SERVICE',
    'ChronoTrade Motion',
    'chronotrade-motion',
    'Creer des pubs courtes, contenus video, animations de logo et assets motion pour les reseaux.',
    array['publicite courte','video courte','motion design','animation logo','reels','tiktok','shorts','ads','contenu social'],
    array['entreprise','createur','commerce','restaurant','marque','independant'],
    array['commerce','restauration','services','digital','bien etre','local business'],
    'sur_devis',
    null,
    false,
    'internal',
    true,
    true,
    '{"universe":"motion","accent":"cyan","cta":"Creer une pub courte","form":"motion"}'::jsonb
  ),
  (
    'PRODUCT',
    'Analyse Express ChronoTrade',
    'analyse-express',
    'Audit court pour comprendre les points forts, les points faibles et les actions prioritaires d un projet.',
    array['audit','analyse','diagnostic','priorites','plan clair','presence digitale','idee','projet'],
    array['entrepreneur','independant','PME','createur','commerce'],
    array['services','commerce','digital','artisanat','restauration','consulting'],
    'fixed',
    29,
    false,
    'internal',
    true,
    true,
    '{"universe":"catalogue","accent":"gold","cta":"Commander Analyse Express","product_slug":"analyse-express"}'::jsonb
  )
on conflict (slug) do update set
  type = excluded.type,
  name = excluded.name,
  description = excluded.description,
  problems_solved = excluded.problems_solved,
  target_users = excluded.target_users,
  industries = excluded.industries,
  price_model = excluded.price_model,
  price = excluded.price,
  recurring = excluded.recurring,
  internal_or_external = excluded.internal_or_external,
  active = excluded.active,
  public = excluded.public,
  metadata = excluded.metadata,
  updated_at = now();
